In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from datetime import datetime, timedelta
from geopy.geocoders import Nominatim

In [2]:
data = pd.read_csv('velibs_export_2024-02-14_12-00.csv')
data

,identifiant_station,nom_station,station_en_fonctionnement,capacité_de_la_station,nombre_bornettes_libres,nombre_total_vélos_disponibles,vélos_mécaniques_disponibles,vélos_électriques_disponibles,borne_de_paiement_disponible,retour_vélib_possible,actualisation_de_la_donnée,coordonnées_géographiques,nom_communes_équipées,code_insee_communes_équipées,update_time
0,44015,Rouget de L'isle - Watteau,OUI,20.0,10.0,10.0,5.0,5.0,OUI,OUI,2024-02-12T12:59:40+01:00,"48.778192750803, 2.3963020229163",Vitry-sur-Seine,NaN,2024-02-12 13:52:17.448525
1,16107,Benjamin Godard - Victor Hugo,OUI,35.0,30.0,5.0,0.0,5.0,OUI,OUI,2024-02-12T12:54:31+01:00,"48.865983, 2.275725",Paris,NaN,2024-02-12 13:52:17.448525
2,9020,Toudouze - Clauzel,OUI,21.0,20.0,1.0,0.0,1.0,OUI,OUI,2024-02-12T12:59:10+01:00,"48.87929591733507, 2.3373600840568547",Paris,NaN,2024-02-12 13:52:17.448525
3,31104,Mairie de Rosny-sous-Bois,OUI,30.0,19.0,9.0,2.0,7.0,OUI,OUI,2024-02-12T13:01:04+01:00,"48.871256519012, 2.4865807592869",Rosny-sous-Bois,NaN,2024-02-12 13:52:17.448525
4,7002,Vaneau - Sèvres,OUI,35.0,16.0,17.0,13.0,4.0,OUI,OUI,2024-02-12T13:00:13+01:00,"48.848563233059, 2.3204218259346",Paris,NaN,2024-02-12 13:52:17.448525
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3885021,32012,Carrefour Pleyel,OUI,36.0,3.0,56.0,16.0,40.0,OUI,OUI,2024-02-14T11:03:57+01:00,"48.92034156960326, 2.3438543826341625",Saint-Denis,NaN,2024-02-14 11:59:38.158478
3885022,4005,Quai des Célestins - Henri IV,OUI,14.0,1.0,13.0,5.0,8.0,OUI,OUI,2024-02-14T11:04:05+01:00,"48.8512971, 2.3624535",Paris,NaN,2024-02-14 11:59:38.158478
3885023,15122,Place Charles Vallin,OUI,26.0,24.0,2.0,0.0,2.0,OUI,OUI,2024-02-14T11:03:10+01:00,"48.835523812041, 2.3025986552238",Paris,NaN,2024-02-14 11:59:38.158478
3885024,4010,Saint-Antoine Sévigné,OUI,26.0,6.0,18.0,9.0,9.0,OUI,OUI,2024-02-14T11:02:30+01:00,"48.8550222, 2.3612322",Paris,NaN,2024-02-14 11:59:38.158478
3885025,8002,Gare Saint-Lazare - Cour du Havre,OUI,45.0,6.0,33.0,16.0,17.0,OUI,OUI,2024-02-14T11:04:16+01:00,"48.875674400851, 2.3265598341823",Paris,NaN,2024-02-14 11:59:38.158478

In [3]:
data.columns

Index(['identifiant_station', 'nom_station', 'station_en_fonctionnement',
       'capacité_de_la_station', 'nombre_bornettes_libres',
       'nombre_total_vélos_disponibles', 'vélos_mécaniques_disponibles',
       'vélos_électriques_disponibles', 'borne_de_paiement_disponible',
       'retour_vélib_possible', 'actualisation_de_la_donnée',
       'coordonnées_géographiques', 'nom_communes_équipées',
       'code_insee_communes_équipées', 'update_time'],
      dtype='object')

In [4]:
df = data.rename(columns={
    'identifiant_station': 'ID',
    'nom_station': 'nom',
    'station_en_fonctionnement': 'status',
    'capacité_de_la_station': 'capacity',
    'nombre_bornettes_libres': 'availability_kiosk',
    'nombre_total_vélos_disponibles': 'availability_bike',
    'vélos_mécaniques_disponibles': 'mbikes_available',
    'vélos_électriques_disponibles': 'ebike_available',
    'borne_de_paiement_disponible': 'payment_possible',
    'retour_vélib_possible': 'return_available',
    'actualisation_de_la_donnée': 'update_time',
    'coordonnées_géographiques': 'coordinates',
    'nom_communes_équipées': 'communes',
    'code_insee_communes_équipées': 'Code_INSEE',
    'update_time': 'collection_time'
})

In [5]:
df.isna().any()

ID                     True
nom                    True
status                 True
capacity               True
availability_kiosk     True
availability_bike      True
mbikes_available       True
ebike_available        True
payment_possible       True
return_available       True
update_time            True
coordinates            True
communes               True
Code_INSEE             True
collection_time       False
dtype: bool

In [6]:
df = df.drop(['collection_time'], axis=1)

In [7]:
df = df.drop_duplicates()

In [8]:
df.shape

(365919, 14)

In [9]:
df = df.drop(['Code_INSEE','payment_possible'], axis=1)

In [10]:
display(df[df['status'].isna()])
df['ID'].unique()

,ID,nom,status,capacity,availability_kiosk,availability_bike,mbikes_available,ebike_available,return_available,update_time,coordinates,communes
213269,--,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
213270,Streaming interrupted due to the following err...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
213773,Streaming interrupted due to the following err...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
323972,Streaming interrupted due to the following err...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
324075,Streaming interrupted due to the following err...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
697884,Streaming interrupted due to the following err...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
846144,Streaming interrupted due to the following err...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
954779,Streaming interrupted due to the following err...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1069270,Streaming interrupted due to the following err...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1178709,Streaming interrupted due to the following err...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1179612,Streaming interrupted due to the following err...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1364279,Streaming interrupted due to the following err...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404910,Streaming interrupted due to the following err...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1461045,Streaming interrupted due to the following err...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1505568,Streaming interrupted due to the following err...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1548927,Streaming interrupted due to the following err...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1642826,Streaming interrupted due to the following err...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1643529,Streaming interrupted due to the following err...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1929612,Streaming interrupted due to the following err...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011799,Streaming interrupted due to the following err...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2271727,Streaming interrupted due to the following err...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2570969,Streaming interrupted due to the following err...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2640876,Streaming interrupted due to the following err...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2882062,Streaming interrupted due to the following err...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3030227,Streaming interrupted due to the following err...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3560989,Streaming interrupted due to the following err...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3674217,Streaming interrupted due to the following err...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

array(['44015', '16107', '9020', ...,
       "Streaming interrupted due to the following error: NotFoundError(404, 'search_phase_execution_exception', 'No search context found for id [459934292]')",
       "Streaming interrupted due to the following error: NotFoundError(404, 'search_phase_execution_exception', 'No search context found for id [492453112]')",
       "Streaming interrupted due to the following error: NotFoundError(404, 'search_phase_execution_exception', 'No search context found for id [492612658]')"],
      dtype=object)

In [11]:
df[df['ID'].apply(lambda x: str(x).isdigit())]['ID'].unique()
df = df[df['ID'].astype(str).str.isdigit()]

In [12]:
df.isna().any()

ID                    False
nom                   False
status                False
capacity              False
availability_kiosk    False
availability_bike     False
mbikes_available      False
ebike_available       False
return_available      False
update_time           False
coordinates           False
communes              False
dtype: bool

In [13]:
df.dtypes

ID                     object
nom                    object
status                 object
capacity              float64
availability_kiosk    float64
availability_bike     float64
mbikes_available      float64
ebike_available       float64
return_available       object
update_time            object
coordinates            object
communes               object
dtype: object

In [14]:
df['status'].unique()

array(['OUI', 'NON'], dtype=object)

In [15]:
df['status'] = pd.Series(df['status']).map({'OUI': True, 'NON': False})
df['return_available'] = pd.Series(df['return_available']).map({'OUI': True, 'NON': False})
df['unavailable'] = (df['status'] == False) | (df['availability_bike'] == 0)

In [16]:
df['status'].unique()

array([ True, False])

In [17]:
df.isna().any()

ID                    False
nom                   False
status                False
capacity              False
availability_kiosk    False
availability_bike     False
mbikes_available      False
ebike_available       False
return_available      False
update_time           False
coordinates           False
communes              False
unavailable           False
dtype: bool

In [18]:
df.shape

(330212, 13)

In [19]:
df.dtypes

ID                     object
nom                    object
status                   bool
capacity              float64
availability_kiosk    float64
availability_bike     float64
mbikes_available      float64
ebike_available       float64
return_available         bool
update_time            object
coordinates            object
communes               object
unavailable              bool
dtype: object

In [20]:
total_stations= df['ID'].nunique()

In [21]:
unavailable_stations = df[(df['status'] == False)]['ID'].unique()
unavailable_stations

array(['51005', '51004', '8001', '17201', '16201', '26010', '31201',
       '31202', '19204'], dtype=object)

In [22]:
df[df['ID'].isin(unavailable_stations)]

,ID,nom,status,capacity,availability_kiosk,availability_bike,mbikes_available,ebike_available,return_available,update_time,coordinates,communes,unavailable
144,51005,Yves Farges - Route d'Enghein,False,0.0,0.0,0.0,0.0,0.0,False,2024-02-06T12:04:01+01:00,"48.95756799268, 2.2834496977978",Argenteuil,True
267,51004,Général Delambre - Prebuard,False,0.0,0.0,0.0,0.0,0.0,False,2024-02-08T07:18:58+01:00,"48.93870344444, 2.2234171606307",Argenteuil,True
515,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-12T12:53:23+01:00,"48.8667692, 2.3157655",Paris,True
547,17201,Porte Maillot - Perreire,False,0.0,0.0,0.0,0.0,0.0,False,2023-09-11T16:39:27+02:00,"48.878021154637, 2.2842371277102",Paris,True
1164,16201,Porte Dauphine,False,0.0,0.0,0.0,0.0,0.0,False,2023-07-28T18:29:09+02:00,"48.871139344351, 2.2749781616017",Paris,True
1372,26010,Louis Armand - Bernard Palissy,False,0.0,0.0,0.0,0.0,0.0,False,2023-01-25T15:17:38+01:00,"48.916925546419, 2.3124207955211",Asnières-sur-Seine,True
1373,31201,Suzanne Masson,False,0.0,0.0,0.0,0.0,0.0,False,2024-01-15T08:20:05+01:00,"48.923306888013, 2.3847292397611",La Courneuve,True
1377,31202,Gabriel Péri - Jules Ferry,False,0.0,0.0,0.0,0.0,0.0,False,2024-01-19T11:21:26+01:00,"48.926182814311, 2.3912295762525",La Courneuve,True
1379,19204,Rampal - Belleville,False,0.0,0.0,0.0,0.0,0.0,False,2023-09-19T10:41:41+02:00,"48.873114661405, 2.3798409114805",Paris,True
18119,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-12T13:53:51+01:00,"48.8667692, 2.3157655",Paris,True
104443,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-12T14:54:19+01:00,"48.8667692, 2.3157655",Paris,True
192268,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-12T15:54:51+01:00,"48.8667692, 2.3157655",Paris,True
277219,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-12T16:55:17+01:00,"48.8667692, 2.3157655",Paris,True
361204,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-12T17:56:43+01:00,"48.8667692, 2.3157655",Paris,True
447649,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-12T18:57:11+01:00,"48.8667692, 2.3157655",Paris,True
533950,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-12T19:57:39+01:00,"48.8667692, 2.3157655",Paris,True
618858,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-12T20:58:05+01:00,"48.8667692, 2.3157655",Paris,True
704262,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-12T21:58:30+01:00,"48.8667692, 2.3157655",Paris,True
790640,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-12T22:58:56+01:00,"48.8667692, 2.3157655",Paris,True
875954,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-12T23:59:19+01:00,"48.8667692, 2.3157655",Paris,True
961152,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-13T00:59:42+01:00,"48.8667692, 2.3157655",Paris,True
1047513,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-13T02:00:11+01:00,"48.8667692, 2.3157655",Paris,True
1134250,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-13T03:00:33+01:00,"48.8667692, 2.3157655",Paris,True
1219699,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-13T04:00:56+01:00,"48.8667692, 2.3157655",Paris,True
1306050,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-13T05:01:18+01:00,"48.8667692, 2.3157655",Paris,True
1391168,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-13T06:02:28+01:00,"48.8667692, 2.3157655",Paris,True
1474736,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-13T07:02:52+01:00,"48.8667692, 2.3157655",Paris,True
1558220,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-13T07:53:12+01:00,"48.8667692, 2.3157655",Paris,True
1643374,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-13T08:53:40+01:00,"48.8667692, 2.3157655",Paris,True
1726067,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-13T09:54:17+01:00,"48.8667692, 2.3157655",Paris,True
1762650,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-13T10:54:46+01:00,"48.8667692, 2.3157655",Paris,True
1838764,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-13T11:55:13+01:00,"48.8667692, 2.3157655",Paris,True
1925154,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-13T13:01:01+01:00,"48.8667692, 2.3157655",Paris,True
2010668,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-13T14:01:00+01:00,"48.8667692, 2.3157655",Paris,True
2094365,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-13T15:01:00+01:00,"48.8667692, 2.3157655",Paris,True
2180728,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-13T15:57:08+01:00,"48.8667692, 2.3157655",Paris,True
2268525,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-13T16:57:34+01:00,"48.8667692, 2.3157655",Paris,True
2352825,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-13T17:59:13+01:00,"48.8667692, 2.3157655",Paris,True
2439169,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-13T18:59:40+01:00,"48.8667692, 2.3157655",Paris,True
2524072,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-13T20:00:05+01:00,"48.8667692, 2.3157655",Paris,True
2609526,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-13T21:00:33+01:00,"48.8667692, 2.3157655",Paris,True
2695612,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-13T22:00:59+01:00,"48.8667692, 2.3157655",Paris,True
2781934,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-13T23:01:24+01:00,"48.8667692, 2.3157655",Paris,True
2868248,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-14T00:01:51+01:00,"48.8667692, 2.3157655",Paris,True
2954317,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-14T01:02:24+01:00,"48.8667692, 2.3157655",Paris,True
3038072,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-14T02:02:47+01:00,"48.8667692, 2.3157655",Paris,True
3124421,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-14T03:03:09+01:00,"48.8667692, 2.3157655",Paris,True
3210820,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-14T04:03:34+01:00,"48.8667692, 2.3157655",Paris,True
3297159,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-14T05:03:57+01:00,"48.8667692, 2.3157655",Paris,True
3383604,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-14T05:55:27+01:00,"48.8667692, 2.3157655",Paris,True
3469946,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-14T06:55:49+01:00,"48.8667692, 2.3157655",Paris,True
3556380,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-14T07:56:12+01:00,"48.8667692, 2.3157655",Paris,True
3640564,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-14T08:56:39+01:00,"48.8667692, 2.3157655",Paris,True
3724501,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-14T10:00:16+01:00,"48.8667692, 2.3157655",Paris,True
3809474,8001,Petit Palais,False,46.0,46.0,0.0,0.0,0.0,False,2024-02-14T10:57:44+01:00,"48.8667692, 2.3157655",Paris,True

In [23]:
df.groupby(['ID']).agg({'availability_bike':np.mean})

       availability_bike
ID
10001          11.869707
10003           7.632075
10004          17.184211
10005           7.911932
10006          13.638776
...                  ...
92004          16.389831
92005          21.022901
92006           5.030612
92007           6.164179
92008          13.500000

[1463 rows x 1 columns]

In [24]:
df.groupby(['ID']).agg({'availability_bike':np.mean}).mean()

availability_bike    12.210632
dtype: float64

In [25]:
df = df.sort_values(by=['ID', 'update_time'])
grouped = df.groupby('ID')
df['unavailability_diff'] = grouped['unavailable'].diff()
df['unavailability_diff'] .unique()

array([nan, 0, 1, -1], dtype=object)

In [26]:
df

,ID,nom,status,capacity,availability_kiosk,availability_bike,mbikes_available,ebike_available,return_available,update_time,coordinates,communes,unavailable,unavailability_diff
1374,10001,René Boulanger - Lancry,True,62.0,49.0,8.0,4.0,4.0,True,2024-02-12T13:00:54+01:00,"48.8685433, 2.3600032",Paris,False,NaN
2818,10001,René Boulanger - Lancry,True,62.0,50.0,7.0,4.0,3.0,True,2024-02-12T13:00:54+01:00,"48.8685433, 2.3600032",Paris,False,0
8633,10001,René Boulanger - Lancry,True,62.0,51.0,6.0,4.0,2.0,True,2024-02-12T13:00:54+01:00,"48.8685433, 2.3600032",Paris,False,0
13030,10001,René Boulanger - Lancry,True,62.0,49.0,8.0,6.0,2.0,True,2024-02-12T13:00:54+01:00,"48.8685433, 2.3600032",Paris,False,0
16007,10001,René Boulanger - Lancry,True,62.0,50.0,7.0,5.0,2.0,True,2024-02-12T13:00:54+01:00,"48.8685433, 2.3600032",Paris,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3680341,92008,Hôtel de Ville de Nanterre,True,38.0,24.0,13.0,9.0,4.0,True,2024-02-14T09:04:06+01:00,"48.892371898250424, 2.205548956990242",Nanterre,False,0
3681818,92008,Hôtel de Ville de Nanterre,True,38.0,25.0,12.0,7.0,5.0,True,2024-02-14T09:04:06+01:00,"48.892371898250424, 2.205548956990242",Nanterre,False,0
3724304,92008,Hôtel de Ville de Nanterre,True,38.0,22.0,15.0,10.0,5.0,True,2024-02-14T09:59:48+01:00,"48.892371898250424, 2.205548956990242",Nanterre,False,0
3740335,92008,Hôtel de Ville de Nanterre,True,38.0,21.0,16.0,10.0,6.0,True,2024-02-14T09:59:48+01:00,"48.892371898250424, 2.205548956990242",Nanterre,False,0
3809155,92008,Hôtel de Ville de Nanterre,True,38.0,21.0,16.0,10.0,6.0,True,2024-02-14T11:00:40+01:00,"48.892371898250424, 2.205548956990242",Nanterre,False,0

In [27]:
changed_stations = df[(df['availability_bike'] == 0) & (df['unavailability_diff'] != 0)]['ID'].unique()

len(changed_stations)

640

In [28]:
#df['ID'].value_counts()

In [29]:
grouped = df.groupby('ID').agg(count=('ID', 'count'))

grouped = grouped.sort_values(by=['count'], ascending=False)
grouped[grouped['count']>1]

       count
ID
12151    749
8002     744
5026     602
43005    594
11001    588
...      ...
8001      47
8025      47
18134     47
18203     47
15063      2

[1432 rows x 1 columns]

In [30]:
#df[df['ID'].isin(grouped[grouped['count'] > 1].index)]

In [31]:
#df[df.groupby('ID')['ID'].transform('count') > 1]

In [32]:
#threshold = pd.Timedelta(minutes=30)

In [33]:
df['update_time'] = pd.to_datetime(df['update_time'])

In [34]:
df = df.sort_values(by=['update_time','nom'])
df['update_time'].min()

Timestamp('2017-12-07 12:18:58+0100', tz='UTC+01:00')

In [35]:
lower_date = pd.Timestamp('2024-02-12 00:00:00+0100', tz='UTC+01:00')

In [36]:
df = df[df['update_time'] >= lower_date]

In [37]:
df

,ID,nom,status,capacity,availability_kiosk,availability_bike,mbikes_available,ebike_available,return_available,update_time,coordinates,communes,unavailable,unavailability_diff
1381,15062,Convention - Lourmel,True,36.0,36.0,0.0,0.0,0.0,False,2024-02-12 07:55:23+01:00,"48.842055041656, 2.2859910875559",Paris,True,NaN
45,16138,Saint-Cloud - Hippodrome,True,30.0,29.0,0.0,0.0,0.0,True,2024-02-12 12:52:22+01:00,"48.85772148887421, 2.2549109905958176",Paris,True,NaN
4439,16138,Saint-Cloud - Hippodrome,True,30.0,28.0,1.0,0.0,1.0,True,2024-02-12 12:52:22+01:00,"48.85772148887421, 2.2549109905958176",Paris,False,-1
1199,15050,Dominique Pado - Croix Nivert,True,22.0,19.0,3.0,1.0,2.0,True,2024-02-12 12:52:25+01:00,"48.83648798164934, 2.2897250577807426",Paris,False,NaN
4208,15050,Dominique Pado - Croix Nivert,True,22.0,18.0,4.0,2.0,2.0,True,2024-02-12 12:52:25+01:00,"48.83648798164934, 2.2897250577807426",Paris,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3867379,17127,Porte de Clichy - Place des Nations Unies,True,40.0,20.0,18.0,15.0,3.0,True,2024-02-14 11:04:22+01:00,"48.896737263309504, 2.310542999196392",Paris,False,0
3873231,17127,Porte de Clichy - Place des Nations Unies,True,40.0,21.0,17.0,15.0,2.0,True,2024-02-14 11:04:22+01:00,"48.896737263309504, 2.310542999196392",Paris,False,0
3881995,17127,Porte de Clichy - Place des Nations Unies,True,40.0,22.0,16.0,15.0,1.0,True,2024-02-14 11:04:22+01:00,"48.896737263309504, 2.310542999196392",Paris,False,0
3811625,13023,Bobillot - Moulin des Prés,True,28.0,27.0,1.0,0.0,1.0,True,2024-02-14 11:04:23+01:00,"48.828657346203, 2.353020646317",Paris,False,-1
3814561,13023,Bobillot - Moulin des Prés,True,28.0,28.0,0.0,0.0,0.0,True,2024-02-14 11:04:23+01:00,"48.828657346203, 2.353020646317",Paris,True,1

In [38]:
df[df['ID']=='16138']

,ID,nom,status,capacity,availability_kiosk,availability_bike,mbikes_available,ebike_available,return_available,update_time,coordinates,communes,unavailable,unavailability_diff
45,16138,Saint-Cloud - Hippodrome,True,30.0,29.0,0.0,0.0,0.0,True,2024-02-12 12:52:22+01:00,"48.85772148887421, 2.2549109905958176",Paris,True,NaN
4439,16138,Saint-Cloud - Hippodrome,True,30.0,28.0,1.0,0.0,1.0,True,2024-02-12 12:52:22+01:00,"48.85772148887421, 2.2549109905958176",Paris,False,-1
17599,16138,Saint-Cloud - Hippodrome,True,30.0,28.0,1.0,0.0,1.0,True,2024-02-12 13:52:51+01:00,"48.85772148887421, 2.2549109905958176",Paris,False,0
55668,16138,Saint-Cloud - Hippodrome,True,30.0,29.0,0.0,0.0,0.0,True,2024-02-12 13:52:51+01:00,"48.85772148887421, 2.2549109905958176",Paris,True,1
98136,16138,Saint-Cloud - Hippodrome,True,30.0,28.0,1.0,1.0,0.0,True,2024-02-12 13:52:51+01:00,"48.85772148887421, 2.2549109905958176",Paris,False,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3724034,16138,Saint-Cloud - Hippodrome,True,30.0,26.0,3.0,2.0,1.0,True,2024-02-14 09:59:17+01:00,"48.85772148887421, 2.2549109905958176",Paris,False,0
3786987,16138,Saint-Cloud - Hippodrome,True,30.0,25.0,4.0,2.0,2.0,True,2024-02-14 09:59:17+01:00,"48.85772148887421, 2.2549109905958176",Paris,False,0
3808952,16138,Saint-Cloud - Hippodrome,True,30.0,25.0,4.0,2.0,2.0,True,2024-02-14 10:59:27+01:00,"48.85772148887421, 2.2549109905958176",Paris,False,0
3844067,16138,Saint-Cloud - Hippodrome,True,30.0,24.0,5.0,2.0,3.0,True,2024-02-14 10:59:27+01:00,"48.85772148887421, 2.2549109905958176",Paris,False,0
3845550,16138,Saint-Cloud - Hippodrome,True,30.0,23.0,6.0,2.0,4.0,True,2024-02-14 10:59:27+01:00,"48.85772148887421, 2.2549109905958176",Paris,False,0

In [39]:
df.dtypes

ID                      object
nom                     object
status                    bool
capacity               float64
availability_kiosk     float64
availability_bike      float64
mbikes_available       float64
ebike_available        float64
return_available          bool
update_time             object
coordinates             object
communes                object
unavailable               bool
unavailability_diff     object
dtype: object

In [40]:
df['unavailability_diff'] = df['unavailability_diff'].fillna(0)
df['unavailability_diff'] = df['unavailability_diff'].astype(int)

In [41]:
def calculate_unavailable_durations(df):
    result_data = []
    grouped = df.groupby('ID')
    
    for group_name, group_df in grouped:
        sorted_group_df = group_df.sort_values('update_time')
        
        unavailable_time = None
        for index, row in sorted_group_df.iterrows():
            if row['unavailable'] == True and row['unavailability_diff'] == 1:
                unavailable_time = pd.to_datetime(row['update_time'])
            elif row['unavailability_diff'] == -1 and unavailable_time is not None:
                available_time = pd.to_datetime(row['update_time'])
                unavailable_duration = available_time - unavailable_time
                if unavailable_duration > pd.Timedelta(0):
                    result_data.append({
                        'ID': group_name, 
                        'nom': group_df['nom'].iloc[0], 
                        'coordinates': group_df['coordinates'].iloc[0], 
                        'communes': group_df['communes'].iloc[0], 
                        'capacity': group_df['capacity'].iloc[0], 
                        'available_time': available_time,
                        'unavailable_time': unavailable_time,
                        'unavailable_duration': unavailable_duration
                    })
                unavailable_time = None

    result_df = pd.DataFrame(result_data)
    return result_df

In [42]:
durations = calculate_unavailable_durations(df)
durations = durations[durations['unavailable_duration']>'0 days 0:01:00']

In [43]:
durations

,ID,nom,coordinates,communes,capacity,available_time,unavailable_time,unavailable_duration
0,10003,Hauteville - Bonne Nouvelle,"48.87077436024, 2.3496496368327",Paris,17.0,2024-02-13 23:01:39+01:00,2024-02-13 22:03:47+01:00,0 days 00:57:52
1,10003,Hauteville - Bonne Nouvelle,"48.87077436024, 2.3496496368327",Paris,17.0,2024-02-14 05:03:02+01:00,2024-02-14 04:02:41+01:00,0 days 01:00:21
2,10009,Mairie du 10ème,"48.872089449907, 2.3575825989246",Paris,19.0,2024-02-12 15:53:11+01:00,2024-02-12 14:51:43+01:00,0 days 01:01:28
3,10009,Mairie du 10ème,"48.872089449907, 2.3575825989246",Paris,19.0,2024-02-12 17:00:10+01:00,2024-02-12 15:53:11+01:00,0 days 01:06:59
4,10013,Alibert - Jemmapes,"48.871044051984, 2.3661044619878",Paris,60.0,2024-02-14 09:59:01+01:00,2024-02-14 09:01:31+01:00,0 days 00:57:30
...,...,...,...,...,...,...,...,...
1445,9117,Bellefond - Maubeuge,"48.878255397645, 2.3452642187476",Paris,31.0,2024-02-13 17:00:52+01:00,2024-02-13 15:03:28+01:00,0 days 01:57:24
1446,9117,Bellefond - Maubeuge,"48.878255397645, 2.3452642187476",Paris,31.0,2024-02-14 10:00:45+01:00,2024-02-14 09:00:11+01:00,0 days 01:00:34
1447,92006,Place Nelson Mandela,"48.897874318180556, 2.2182820737361912",Nanterre,30.0,2024-02-13 21:01:10+01:00,2024-02-13 19:00:17+01:00,0 days 02:00:53
1448,92007,Pesaro - Préfecture,"48.89577046284005, 2.223908342421055",Nanterre,22.0,2024-02-12 21:56:37+01:00,2024-02-12 20:56:11+01:00,0 days 01:00:26
1449,92007,Pesaro - Préfecture,"48.89577046284005, 2.223908342421055",Nanterre,22.0,2024-02-13 17:58:54+01:00,2024-02-13 16:56:56+01:00,0 days 01:01:58

In [44]:
df[df['ID'] == '9117'].tail(20)

,ID,nom,status,capacity,availability_kiosk,availability_bike,mbikes_available,ebike_available,return_available,update_time,coordinates,communes,unavailable,unavailability_diff
3589291,9117,Bellefond - Maubeuge,True,31.0,22.0,5.0,3.0,2.0,True,2024-02-14 08:04:14+01:00,"48.878255397645, 2.3452642187476",Paris,False,0
3592208,9117,Bellefond - Maubeuge,True,31.0,23.0,4.0,2.0,2.0,True,2024-02-14 08:04:14+01:00,"48.878255397645, 2.3452642187476",Paris,False,0
3595145,9117,Bellefond - Maubeuge,True,31.0,24.0,3.0,2.0,1.0,True,2024-02-14 08:04:14+01:00,"48.878255397645, 2.3452642187476",Paris,False,0
3603922,9117,Bellefond - Maubeuge,True,31.0,26.0,1.0,1.0,0.0,True,2024-02-14 08:04:14+01:00,"48.878255397645, 2.3452642187476",Paris,False,0
3612709,9117,Bellefond - Maubeuge,True,31.0,27.0,1.0,1.0,0.0,True,2024-02-14 08:04:14+01:00,"48.878255397645, 2.3452642187476",Paris,False,0
3628829,9117,Bellefond - Maubeuge,True,31.0,26.0,2.0,1.0,1.0,True,2024-02-14 08:04:14+01:00,"48.878255397645, 2.3452642187476",Paris,False,0
3640529,9117,Bellefond - Maubeuge,True,31.0,26.0,2.0,1.0,1.0,True,2024-02-14 09:00:11+01:00,"48.878255397645, 2.3452642187476",Paris,False,0
3649315,9117,Bellefond - Maubeuge,True,31.0,26.0,1.0,0.0,1.0,True,2024-02-14 09:00:11+01:00,"48.878255397645, 2.3452642187476",Paris,False,0
3652242,9117,Bellefond - Maubeuge,True,31.0,27.0,1.0,0.0,1.0,True,2024-02-14 09:00:11+01:00,"48.878255397645, 2.3452642187476",Paris,False,0
3658095,9117,Bellefond - Maubeuge,True,31.0,27.0,0.0,0.0,0.0,True,2024-02-14 09:00:11+01:00,"48.878255397645, 2.3452642187476",Paris,True,1
3724441,9117,Bellefond - Maubeuge,True,31.0,27.0,0.0,0.0,0.0,True,2024-02-14 10:00:45+01:00,"48.878255397645, 2.3452642187476",Paris,True,0
3752292,9117,Bellefond - Maubeuge,True,31.0,26.0,1.0,1.0,0.0,True,2024-02-14 10:00:45+01:00,"48.878255397645, 2.3452642187476",Paris,False,-1
3790376,9117,Bellefond - Maubeuge,True,31.0,26.0,1.0,0.0,1.0,True,2024-02-14 10:00:45+01:00,"48.878255397645, 2.3452642187476",Paris,False,0
3802025,9117,Bellefond - Maubeuge,True,31.0,25.0,2.0,0.0,2.0,True,2024-02-14 10:00:45+01:00,"48.878255397645, 2.3452642187476",Paris,False,0
3809422,9117,Bellefond - Maubeuge,True,31.0,26.0,1.0,0.0,1.0,True,2024-02-14 11:01:50+01:00,"48.878255397645, 2.3452642187476",Paris,False,0
3821057,9117,Bellefond - Maubeuge,True,31.0,25.0,2.0,1.0,1.0,True,2024-02-14 11:01:50+01:00,"48.878255397645, 2.3452642187476",Paris,False,0
3832840,9117,Bellefond - Maubeuge,True,31.0,26.0,2.0,1.0,1.0,True,2024-02-14 11:01:50+01:00,"48.878255397645, 2.3452642187476",Paris,False,0
3853279,9117,Bellefond - Maubeuge,True,31.0,26.0,1.0,1.0,0.0,True,2024-02-14 11:01:50+01:00,"48.878255397645, 2.3452642187476",Paris,False,0
3869377,9117,Bellefond - Maubeuge,True,31.0,27.0,1.0,1.0,0.0,True,2024-02-14 11:01:50+01:00,"48.878255397645, 2.3452642187476",Paris,False,0
3872346,9117,Bellefond - Maubeuge,True,31.0,27.0,0.0,0.0,0.0,True,2024-02-14 11:01:50+01:00,"48.878255397645, 2.3452642187476",Paris,True,1

In [45]:
durations[durations['ID'] == '9117']

,ID,nom,coordinates,communes,capacity,available_time,unavailable_time,unavailable_duration
1442,9117,Bellefond - Maubeuge,"48.878255397645, 2.3452642187476",Paris,31.0,2024-02-12 20:00:50+01:00,2024-02-12 19:02:38+01:00,0 days 00:58:12
1443,9117,Bellefond - Maubeuge,"48.878255397645, 2.3452642187476",Paris,31.0,2024-02-13 08:56:57+01:00,2024-02-13 08:02:27+01:00,0 days 00:54:30
1444,9117,Bellefond - Maubeuge,"48.878255397645, 2.3452642187476",Paris,31.0,2024-02-13 10:58:04+01:00,2024-02-13 09:57:37+01:00,0 days 01:00:27
1445,9117,Bellefond - Maubeuge,"48.878255397645, 2.3452642187476",Paris,31.0,2024-02-13 17:00:52+01:00,2024-02-13 15:03:28+01:00,0 days 01:57:24
1446,9117,Bellefond - Maubeuge,"48.878255397645, 2.3452642187476",Paris,31.0,2024-02-14 10:00:45+01:00,2024-02-14 09:00:11+01:00,0 days 01:00:34

In [46]:
problematic_stations = durations[durations['unavailable_duration']>'0 days 0:30:00']['nom'].unique()

In [47]:
problematic_stations

array(['Hauteville - Bonne Nouvelle', 'Mairie du 10ème',
       'Alibert - Jemmapes', 'Récollets - Square Villemin',
       'Marché Saint-Quentin', "Gare de l'Est - Verdun",
       'Jemmapes - Ecluses Saint-Martin', 'Dunkerque - Alsace',
       'Gare du Nord - Dunkerque', 'Dunkerque - Rocroy',
       'Claude Vellefaux - Hôpital Saint-Louis', 'Quai de Valmy',
       'Gare du Nord - La Chapelle', 'Louis Blanc - Jemmapes',
       'Granges aux Belles', 'Gare du Nord - Faubourg Saint-Denis',
       'Gare du Nord - Denain', "Gare de l'Est - Faubourg-Saint-Martin",
       'Alexandre Parodi - Quai de Valmy', 'Gare du Nord - Demarquay',
       'Claude Vellefaux - Sambre et Meuse', 'Strasbourg - Saint-Denis',
       'Halles - Bourdonnais', 'Jean-Pierre Timbaud - Vaucouleurs',
       'Parmentier - Fontaine au Roi',
       'Charonne - Robert et Sonia Delaunay', 'Parmentier - République',
       'Cossonnerie - Sébastopol',
       'Faubourg St-Antoine - Place de la Nation', 'Montgallet - Reuilly',
       'Saint-Mande - Picpus', "Saint-Mandé - Fabre d'Eglantine",
       'Gare de Reuilly - Picpus', 'Gare de Bercy',
       'Terroirs de France - Lheureux', 'Niger - Soult', 'Dugommier',
       'Arago - Glacière', "Place d'Italie - Soeur Rosalie",
       "Place d'Italie - Vincent Auriol", 'Hôpital - Campo-Formio',
       'Saint-Marcel - Hôpital', 'Nationale - Vincent Auriol',
       'Butte aux Cailles - Esperance', 'Bobillot - Moulin des Prés',
       'Bobillot - Tolbiac', 'Place Jean Delay',
       'Mazagran - Pierre de Coubertin', 'Italie - Tolbiac',
       'Ivry - Baudricourt', 'Ivry - Simone Weil',
       'Vincent Auriol - Louise Weiss',
       'Halle Freyssinet - Parvis Alan Turing',
       'M.- A. Lagroua Weill-Hallé -  F. Dolto',
       'Croulebarde - Corvisart', 'Hôpital Pitié Salpêtrière',
       'Bobillot - Paulin Mery', 'Brillat-Savarin - Küss',
       'Moulin de la Pointe', 'Nationale - Marcel Duchamp',
       'Place Nationale - Château-des-Rentiers',
       'Auguste Blanqui - Glacière', 'Edgar Quinet - Gaité',
       'Edgar Quinet - Raspail', 'Schoelcher - Raspail',
       'Saint-Jacques - Tombe Issoire',
       'Mouton Duvernet - Général Leclerc', 'Tombe Issoire - René Coty',
       'Jean Moulin - Place Victor et Hélène Basch',
       "Place des Droits de l'Enfant", 'Liard - Amiral Mouchez',
       'René Coty - Parc Montsouris', "Porte d'Orléans",
       'Didot - Mariniers', 'Adolphe Pinard - Victor Hugo',
       'Jacquier - Didot', 'Plantes - Moulin Vert',
       'Pernety - Raymond Losserand', 'Mairie du 14ème',
       'Ouest - Château', 'Maine - Jean Zay', 'Boulard - Daguerre',
       'Gare Montparnasse - Edgar Quinet', 'Maine - Liancourt',
       'Boyer-Barret - Raymond Losserand',
       'Marc Sangnier - Porte de Vanves', 'Le Brix et Mesmin - Jourdan',
       'Cassini - Denfert-Rochereau', 'Méchain - Faubourg Saint-Jacques',
       'Santé - Arago', 'Romain Rolland', 'Colonel Monteil - Brune',
       'David Weill - Parc Montsouris', 'Odessa - Départ',
       'Jonquoy - Didot', 'Jourdan - Monticelli',
       'Bézout - Général Leclerc', 'Froidevaux - Boulard',
       'Jourdan - Cité Universitaire', 'Auguste Cain - Jean Moulin',
       'Pierre Larousse - Raymond Losserand', 'Decrès - Alésia',
       'Gare Montparnasse - Arrivée', 'Maine - Antoine Bourdelle',
       'Vaugirard - Pasteur', 'Place Jacques et Thérèse Tréfouël',
       'Cherche-Midi - Hôpital Necker', 'Cambronne - Mademoiselle',
       'Volontaires - Vaugirard', 'Place Falguière',
       'Dutot - Place Alleray', 'Paul Barruel - Vaugirard',
       'Suffren - La Motte-Piquet', 'Duhamel - André Gide',
       'Abbé Groult - Convention', 'Franquet - Labrouste',
       'Brancion - Lefebvre', 'Dantzig - Lefebvre',
       'Parc Georges Brassens - Brancion', 'Morillons - Dantzig',
       'Dominique Pado - Croix Nivert', 'Fédération - Suffren',
       'Lourmel - Marie Skobtsov', 'Vigée-Lebrun - Anselme Payen',
       'Arsonval - Falguière', 'Place Charles Vallin', 'Bargue -  Dutot',
       'Saint Lambert - Blomet', 'Bracion - Périphérique',
       'Pergolèse - Malakoff', 'André Maurois - Joseph et Marie Hackin',
       'Raymond Poincaré - Place Victor Hugo', 'Lauriston - Copernic',
       "Longchamp - Place d'Iéna", 'Galilée - Kléber',
       'Saint-Didier - Raymond Poincaré',
       'Belles Feuilles - Place de Mexico', 'Eylau - Trocadéro',
       'Bassano -  Iéna', 'Flandrin - Henri Martin',
       'Place de la Porte de Passy', 'François Ponsard - La Muette',
       'Jean Bologne - Passy', 'Passy - Place du Costa Rica',
       'Ranelagh - Mozart', 'Mozart - Jasmin', 'Vignes - Boulainvilliers',
       "Eglise d'Auteuil", "Porte d'Auteuil", 'Molitor - Michel-Ange',
       'Exelmans - Michel-Ange', 'Place de Passy', 'Pergolèse - Marbeau',
       'Paul Valery - Victor Hugo', 'Crevaux - Bugeaud',
       'Benjamin Godard - Victor Hugo', 'Sablons - Georges Mandel',
       'Octave Feuillet - Albéric Magnard',
       'Faustin Hélie - Desbordes-Valmore', 'Chernoviz - Raynouard',
       'Raffet - Montmorency', 'Ceinture du Lac Inferieure - Saint-Cloud',
       'Saint-Cloud - Hippodrome', 'Fragonard - Porte de Clichy',
       'Legendre - Dulong', 'Parc Monceau', 'Phalsbourg - Villiers',
       'Pereire - Place de Wagram',
       'Jean Oestreicher - Porte de Champerret', 'Bayen - Pereire',
       'Place Saint-Ferdinand', 'Belidor - Gouvion-Saint-Cyr',
       'Porte de Saint-Ouen - Bessières', 'De Toqueville - Terrasse',
       'Batignolles - Abel Truchet', 'Alfred Roll - Berthier',
       'Jardin Marguerite Long', 'Berthier - Porte de Clichy',
       'Berthier - Place Stuart Merril', 'Legendre - Nollet',
       'Lemercier - Cardinet', 'Pereire - Saussure',
       'Square des Epinettes', 'Bridaine - Lamandé',
       'Mstislav Rostropovitch - Berthier',
       'Marie-Georges Picquart - Pereire', 'Mariotte - Batignolles',
       'Place de la Porte de Champeret', 'Damrémont - Caulaincourt',
       'Cimetière de Montmartre', 'Place des Abbesses',
       'Tardieu - Chappe', 'Stephenson - Doudeauville',
       'Léon - Doudeauville', 'Custine - Ramey',
       'Francoeur - Caulaincourt',
       'Caulaincourt - Place Constantin Pecqueur',
       'Square Raymond Souplex', 'Francoeur - Marcadet',
       'Marcadet - Ramey', 'Marcadet - Barbès', 'Ordener - Poissonniers',
       'Clignancourt - Ordener', 'Mairie du 18ème', 'Ruisseau - Ordener',
       'Emile Blemont - Poteau', 'Joseph Dijon - Ornano',
       'Leibniz - Jean Dollfus', 'Rochechouart - Martyrs',
       'Place Pigalle', 'Clichy - Place Blanche', 'Clichy - Douai',
       'Pierre Ginier - Clichy', 'Etienne Jodelle - Saint Ouen',
       'Chartres - La Charbonnière', "Lepic - Armée d'Orient",
       'Véron - Lepic', 'Clignancourt - Sofia', 'Quai de la Seine',
       'Flandre - Riquet', 'Emile Reynaud - Porte de la Villette',
       'Lally-Tollendal - Armand Carrel', 'Laumière - Petit',
       'Thionville - Ourcq', 'Hautpoul - Jean Jaurès', 'Petit - Manin',
       'Manin - Simon Bolivar', 'Botzaris - Parc des Buttes Chaumont',
       'Botzaris - Crimée', 'Place de Rhin et Danube', 'Serrurier',
       'Seine - Flandre', 'Manin - Crimée', 'Hôpital Robert Debré',
       'Belleville - Porte des Lilas', 'Lassus - Delouvain',
       'Belleville - Télégraphe', 'Belleville - Pyrénées',
       'Square Simon Bolivar', "Manin - Carrières d'Amérique",
       'Ambroise Rendu - Porte Brunet', 'Pré Saint-Gervais - Lilas',
       'Manin - Secrétan', 'Carducci - Place Hannah Arendt',
       'Belleville -  Pré Saint-Gervais', 'Metz - Marne',
       'Alexander Fleming - Belvédère', "Place de l'Édit de Nantes",
       'Aubervilliers - Curial', 'Solitaires - Place des Fêtes',
       'Place Paul Delouvrier', 'Petit - Georges Thill',
       'Square de la rue Pixérécourt', 'Pyrénées - Plaine',
       'Pyrénées - Avron', 'Pyrénées - Dagorno', 'Buzenval - Vignoles',
       'Pyrénées - Maraîchers', 'Saint-Blaise - Mouraud',
       'Place du Maquis du Vercors', 'Pyrénées - Charles Renouvier',
       'Indre - Prairies', 'Porte de Bagnolet', 'Pelleport - Belgrand',
       'Gambetta - Père Lachaise', 'Porte de Ménilmontant',
       'Frères Flavien - Porte des Lilas', 'Square des Amandiers',
       'Sorbier - Ménilmontant', 'Pyrénées - Ménilmontant',
       'Ménilmontant - Pelleport', 'Gambetta - Saint Fargeau',
       'Belleville - Couronnes', 'Parc de Belleville - Julien Lacroix',
       'Pyrénées - Emmery', 'Davout - Volga', 'Louis Ganne - Davout',
       'Cours de Vincennes - Davout', 'Mairie du 2ème',
       'Uzès - Montmartre', 'Le Vau - Maurice Bertaux', 'Mairie du 20ème',
       "Jardin de l'Hospice Debrousse", 'Haxo - Surmelin',
       "Villiers de l'Isle Adam - Pyrénées",
       'Jourdain - Place des Grandes Rigoles',
       'Piat - Parc de Belleville', 'Louis Lumière - Porte de Bagnolet',
       'Haies - Réunion', 'Saint-Fargeau - Mortier', 'Orteaux - Mouraud',
       'Square des Saint-Simoniens', 'Choiseul - Quatre Septembre',
       'Boyer - Ménilmontant', 'Vitruve - Davout', 'Favart - Italiens',
       'Repos - Cimetière du Père Lachaise', 'Réunion - Avron',
       'Lieutenant Chauré - Etienne Marey', 'Henri Chevreau - Couronnes',
       'Borrégo - Gambetta', 'Daunou - Louis le Grand',
       'Mûriers - Père Lachaise', 'Ramponeau - Belleville',
       'Louis le Grand - Italiens', 'Danielle Casanova - Opéra',
       'Eugène Reisz - Davout', "Dupont de l'Eure - Gambetta",
       'Transvaal - Charles de Gaulle',
       'Jean Jaurès - Jean Baptiste Clément', 'Jean Jaurès - Reine',
       'Victor Hugo - Galliéni', 'Point du Jour - Jean Jaurès',
       'Billancourt - Général Leclerc', 'Fessart - Château',
       'Réaumur - Montmartre', 'Guichet - Jean Jaurès',
       'Chancé Milly - Cimetière Communal Sud',
       'Bibliothèque Nationale - Richelieu', 'Place Jules Ferry',
       "Estienne d'Orves - Henri Ginoux", 'Arthur Auger - Jean Jaurès',
       'Verdier - République', 'Molière - République',
       'Marne - Germain Dardan', 'Vanne - Général de Gaulle',
       'Verdier - Jean Jaurès', 'Louis Lejeune - Barbès',
       'Gabriel Péri - Place de la Libération',
       'Amaury Duval - Gabriel Péri', 'Lucie Aubrac - Fort',
       'Jules Guesdes - Général de Gaulle',
       "Cimetière d'Issy-les-Moulineaux",
       'Moulin de Pierre - Abbé Grégoire', 'Verger - Colonel Guichard',
       'Mairie de Clamart', 'Édouard Vaillant - Place Jean Jaurès',
       'Maurice Payret-Dortail', 'Fontaine du Tertre - Calvaire',
       'Larmeroux - Baudelaire', 'Gare SNCF Vanves-Malakoff',
       'Place du Maréchal de Lattre de Tassigny',
       'Jean Bleuzen - Square du 11 Novembre', 'Square Etienne Jarousse',
       'Marcel Yol - Jullien', 'Place Centrale', 'Val-Fleury',
       'Madeleine Michelis - Roule', 'Mont Valérien - Michel Salles',
       'Henri Ravera - Gabriel Péri', 'Tertres - Fontaine',
       'Louis Pasteur - Albert Petit', 'Stalingrad - Barbara',
       'Verdun - Henri Barbusse', 'Charles de Gaulle - Plateau de Vanves',
       'Jean Jaurès - Salvador Allende',
       'Pierre Brossolette - Adolphe Pinard',
       'Guy Môquet - Etienne Dolet', 'Place du 14 Juillet',
       'Henri Barbusse - Stalingrad', 'Place de la Division Leclerc',
       'Hôtel de Ville de Fontenay-aux-Roses',
       'Paul Vaillant Couturier - Chaptal', 'Grande Rue - Europe',
       'Pavé des Gardes - Charles Vaillant',
       'Henri Barbusse - Gabriel Péri', 'Division Leclerc - Kléber',
       'Parc des Pierrettes', 'Béranger - Félix Faure', 'Les Blagis',
       'Hôtel de Ville de Chaville', 'Gare de Chaville Rive Gauche',
       'Adolphe Lalyre - Armand Silvestre', 'Place Charles de Gaulle',
       'Jardin Modèle - Pierre Boudou', 'Gare de la Garenne-Colombes',
       'Jean Jaurès - Paul Lafargue', 'Lagny - Auguste Blanqui',
       'François Debergue - Croix de Chavaux',
       'Place Du Général De Gaulle', 'Stalingrad - Désiré Chevalier',
       'Place Carnot', 'Centenaire - Sorins', 'Lucie Aubrac - Franklin',
       'Jean Moulin - Paul Doumer', 'Gambetta - Michelet',
       'Vincennes - Douy-Delcupe', 'Résistance - Parmentier',
       'Place François Mitterand', 'Raspail Barbès',
       'Boissière - Etienne Dolet',
       'Pierre et Marie Curie - Julien Grimau',
       'Sadi Carnot - François Mitterrand', 'Jeanne Hornet - Girardot',
       'Château - République', 'Noisy le Sec - Jean-Baptiste Clément',
       'Saint-Germain - Verdun', 'Porte des Lilas - Faidherbe',
       'Calmette', 'Mairie', 'Gabrielle Josserand - Edouard Vaillant',
       'Place du Président Salvador Allende',
       'Benjamin Delessert - Jean Lolive', 'Candale - Mehul',
       'Guillaume Tell - Parc Henri Barbusse', 'Marcelle - Thalie',
       "Place de l'Hôtel de Ville", 'Place de la vache noire',
       'Stalingrad - Rigollots', 'République - Danton',
       'Maréchal Joffre - Verdun', 'Hôtel de ville de Fontenay-sous-Bois',
       'Louis Xavier de Ricard - Ancienne Mairie', 'Nungesser - Santé',
       'Général De Gaulle - Alouette', 'Général De Gaulle - Vivien',
       'Pierre et Marie Curie - Maurice Thorez',
       'Barbès - Monique Maunoury', 'Verdun - Pierre et Marie Curie',
       'Stalingrad - Germaine Tailleferre', 'Gare Arcueil - Cachan',
       'Vladimir Ilitch Lénine - Andrée Chedid',
       'Charles Gide - Fort de Bicêtre', 'Mairie du Kremlin-Bicêtre',
       'Place Jean-Baptiste Clément', 'Montreuil - République',
       'Hôtel de Ville de Vincennes', 'Place Jean-Spire-Lemaître',
       'La Jarry - Place Diderot', 'Edouard Tremblay - Julian Grimaux',
       'Verdun - Adrien Damalix', 'Chastenet de Géry - Marcel Paul',
       'LCL Campus - Place Oscar Niemeyer',
       'Eugène Varlin - Place de la Paix',
       'Maxime Gorki - Paul Vaillant-Couturier',
       'République - Auguste Perret', "Epi d'Or - Chevilly",
       'Le Goff - Gay-Lussac', 'Gay Lussac - Saint-Jacques',
       'Ecoles - Carmes', 'Estrapade - Ulm', 'Jean Calvin - Tournefort',
       'Boulangers - Cardinal Lemoine', 'Cujas - Saint-Michel',
       'Jussieu - Guy de la Brosse', 'Saint-Michel - Luxembourg',
       'Saint-Benoît - Jacob', 'Montparnasse -  Square Ozanam',
       'Notre-Dame-des-Champs - Stanislas', 'Bréa - Raspail',
       'Guynemer - Jardin du Luxembourg', 'Chevreuse - Montparnasse',
       'Michelet - Assas', 'Beaux-Arts - Bonaparte',
       'Marché Saint-Germain', 'Raspail - Varenne',
       'Las Cases - Bourgogne', 'Galilée - Vernet', 'Liège - Moscou',
       'Clapeyron - Moscou', 'Naples - Rome', 'Batignolles - Beudant',
       'Mairie du 8ème', 'Arsène Houssaye - Champs-Elysées',
       'Berri - Haussmann', 'François 1er - Montaigne',
       'Pierre Charron - Champs-Elysées', 'Georges V - François 1er',
       'Batignolles - Rome', 'Place Georges Guillaumin',
       'Hoche - Tilsitt', 'Lamennais - Washington', 'Artois - Berri',
       'François 1er - Lincoln', 'Gare Saint-Lazare - Stockholm',
       'Arsène Houssaye - Friedland', 'Londres - Europe',
       'George V - Christophe Colomb', 'Gérando - Rochechouart',
       "Square d'Anvers", 'Dunkerque - Trudaine', 'Condorcet - Turgot',
       "Tour d'Auvergne - Rodier", 'Rochechouart lamartine',
       'Rougemont - Poissonnière', 'Lallier - Trudaine',
       'Victor Massé - Jean-Baptiste Pigalle', 'Toudouze - Clauzel',
       'Laffitte - Italiens', 'Jean-Baptiste Pigalle - La Bruyere',
       'Douai - Pierre Fontaine',
       "Saint-Lazare - Place d'Estienne d'Orves", 'Athènes - Clichy',
       'Douai - Bruxelles', "Chaussée d'Antin - Haussmann",
       'Faubourg Poissonnière - Dunkerque', 'Milton - Manuel',
       "Victoire - Chaussée d'Antin", 'Bellefond - Maubeuge',
       'Place Nelson Mandela', 'Pesaro - Préfecture'], dtype=object)

In [48]:
available_stations = df[~df['ID'].isin(unavailable_stations)]['ID'].unique()

In [49]:
(len(problematic_stations)+len(unavailable_stations))/df['ID'].nunique()

0.35614525139664804

In [50]:
durations['unavailable_duration'] = np.ceil(durations['unavailable_duration'].dt.total_seconds() / 60).astype(int)
durations['unavailable_duration'] = durations['unavailable_duration'].fillna(pd.Timedelta(seconds=0))

In [89]:
df['ID'].nunique()

1432

In [51]:
durations

,ID,nom,coordinates,communes,capacity,available_time,unavailable_time,unavailable_duration
0,10003,Hauteville - Bonne Nouvelle,"48.87077436024, 2.3496496368327",Paris,17.0,2024-02-13 23:01:39+01:00,2024-02-13 22:03:47+01:00,58
1,10003,Hauteville - Bonne Nouvelle,"48.87077436024, 2.3496496368327",Paris,17.0,2024-02-14 05:03:02+01:00,2024-02-14 04:02:41+01:00,61
2,10009,Mairie du 10ème,"48.872089449907, 2.3575825989246",Paris,19.0,2024-02-12 15:53:11+01:00,2024-02-12 14:51:43+01:00,62
3,10009,Mairie du 10ème,"48.872089449907, 2.3575825989246",Paris,19.0,2024-02-12 17:00:10+01:00,2024-02-12 15:53:11+01:00,67
4,10013,Alibert - Jemmapes,"48.871044051984, 2.3661044619878",Paris,60.0,2024-02-14 09:59:01+01:00,2024-02-14 09:01:31+01:00,58
...,...,...,...,...,...,...,...,...
1445,9117,Bellefond - Maubeuge,"48.878255397645, 2.3452642187476",Paris,31.0,2024-02-13 17:00:52+01:00,2024-02-13 15:03:28+01:00,118
1446,9117,Bellefond - Maubeuge,"48.878255397645, 2.3452642187476",Paris,31.0,2024-02-14 10:00:45+01:00,2024-02-14 09:00:11+01:00,61
1447,92006,Place Nelson Mandela,"48.897874318180556, 2.2182820737361912",Nanterre,30.0,2024-02-13 21:01:10+01:00,2024-02-13 19:00:17+01:00,121
1448,92007,Pesaro - Préfecture,"48.89577046284005, 2.223908342421055",Nanterre,22.0,2024-02-12 21:56:37+01:00,2024-02-12 20:56:11+01:00,61
1449,92007,Pesaro - Préfecture,"48.89577046284005, 2.223908342421055",Nanterre,22.0,2024-02-13 17:58:54+01:00,2024-02-13 16:56:56+01:00,62

In [52]:
mean_availibility = df.groupby(['ID', 'nom', 'coordinates', 'communes','capacity']).agg({'availability_bike': 'mean'}).reset_index()

In [53]:
total_unavailability = durations.groupby(['ID', 'nom', 'coordinates', 'communes','capacity']).agg({'unavailable_duration': 'sum'}).reset_index()
total_unavailability = pd.merge(total_unavailability, (durations.groupby('ID').agg({'unavailable_duration': 'count'}).reset_index()), on='ID', how='inner')
total_unavailability.rename(columns={'unavailable_duration_x': 'unavailable_duration','unavailable_duration_y': 'unavailable_count'}, inplace=True)
total_unavailability

,ID,nom,coordinates,communes,capacity,unavailable_duration,unavailable_count
0,10003,Hauteville - Bonne Nouvelle,"48.87077436024, 2.3496496368327",Paris,17.0,119,2
1,10009,Mairie du 10ème,"48.872089449907, 2.3575825989246",Paris,19.0,129,2
2,10013,Alibert - Jemmapes,"48.871044051984, 2.3661044619878",Paris,60.0,58,1
3,10016,Récollets - Square Villemin,"48.875034655883944, 2.359801238597928",Paris,17.0,541,7
4,10021,Marché Saint-Quentin,"48.877356057652, 2.3545114456374",Paris,15.0,180,3
...,...,...,...,...,...,...,...
497,9115,Milton - Manuel,"48.878249, 2.341181",Paris,22.0,116,2
498,9116,Victoire - Chaussée d'Antin,"48.875065791004396, 2.3316738009452824",Paris,24.0,243,2
499,9117,Bellefond - Maubeuge,"48.878255397645, 2.3452642187476",Paris,31.0,354,5
500,92006,Place Nelson Mandela,"48.897874318180556, 2.2182820737361912",Nanterre,30.0,121,1
501,92007,Pesaro - Préfecture,"48.89577046284005, 2.223908342421055",Nanterre,22.0,123,2

In [54]:
mean_availibility

,ID,nom,coordinates,communes,capacity,availability_bike
0,10001,René Boulanger - Lancry,"48.8685433, 2.3600032",Paris,62.0,11.869707
1,10003,Hauteville - Bonne Nouvelle,"48.87077436024, 2.3496496368327",Paris,17.0,7.632075
2,10004,Metz - Faubourg Saint-Denis,"48.870893, 2.353521",Paris,48.0,17.184211
3,10005,Petites Ecuries - Faubourg Poissonnière,"48.87397217237368, 2.348388757504776",Paris,17.0,7.911932
4,10006,Petites Ecuries - Faubourg Saint-Denis,"48.87287120589831, 2.3542150855064397",Paris,28.0,13.638776
...,...,...,...,...,...,...
1427,92004,Nanterre - Université,"48.901365, 2.212693",Nanterre,20.0,16.389831
1428,92005,Gare de Nanterre Ville,"48.8950295, 2.1957932",Nanterre,43.0,21.022901
1429,92006,Place Nelson Mandela,"48.897874318180556, 2.2182820737361912",Nanterre,30.0,5.030612
1430,92007,Pesaro - Préfecture,"48.89577046284005, 2.223908342421055",Nanterre,22.0,6.164179
1431,92008,Hôtel de Ville de Nanterre,"48.892371898250424, 2.205548956990242",Nanterre,38.0,13.500000

In [59]:
availability = pd.merge(mean_availibility, total_unavailability, on=['ID', 'nom', 'coordinates', 'communes', 'capacity'], how='left')
availability['unavailable_duration'] = availability['unavailable_duration'].fillna(0)
availability['unavailable_count'] = availability['unavailable_count'].fillna(0)

In [60]:
availability

,ID,nom,coordinates,communes,capacity,availability_bike,unavailable_duration,unavailable_count
0,10001,René Boulanger - Lancry,"48.8685433, 2.3600032",Paris,62.0,11.869707,0.0,0.0
1,10003,Hauteville - Bonne Nouvelle,"48.87077436024, 2.3496496368327",Paris,17.0,7.632075,119.0,2.0
2,10004,Metz - Faubourg Saint-Denis,"48.870893, 2.353521",Paris,48.0,17.184211,0.0,0.0
3,10005,Petites Ecuries - Faubourg Poissonnière,"48.87397217237368, 2.348388757504776",Paris,17.0,7.911932,0.0,0.0
4,10006,Petites Ecuries - Faubourg Saint-Denis,"48.87287120589831, 2.3542150855064397",Paris,28.0,13.638776,0.0,0.0
...,...,...,...,...,...,...,...,...
1427,92004,Nanterre - Université,"48.901365, 2.212693",Nanterre,20.0,16.389831,0.0,0.0
1428,92005,Gare de Nanterre Ville,"48.8950295, 2.1957932",Nanterre,43.0,21.022901,0.0,0.0
1429,92006,Place Nelson Mandela,"48.897874318180556, 2.2182820737361912",Nanterre,30.0,5.030612,121.0,1.0
1430,92007,Pesaro - Préfecture,"48.89577046284005, 2.223908342421055",Nanterre,22.0,6.164179,123.0,2.0
1431,92008,Hôtel de Ville de Nanterre,"48.892371898250424, 2.205548956990242",Nanterre,38.0,13.500000,0.0,0.0

In [61]:
availability

,ID,nom,coordinates,communes,capacity,availability_bike,unavailable_duration,unavailable_count
0,10001,René Boulanger - Lancry,"48.8685433, 2.3600032",Paris,62.0,11.869707,0.0,0.0
1,10003,Hauteville - Bonne Nouvelle,"48.87077436024, 2.3496496368327",Paris,17.0,7.632075,119.0,2.0
2,10004,Metz - Faubourg Saint-Denis,"48.870893, 2.353521",Paris,48.0,17.184211,0.0,0.0
3,10005,Petites Ecuries - Faubourg Poissonnière,"48.87397217237368, 2.348388757504776",Paris,17.0,7.911932,0.0,0.0
4,10006,Petites Ecuries - Faubourg Saint-Denis,"48.87287120589831, 2.3542150855064397",Paris,28.0,13.638776,0.0,0.0
...,...,...,...,...,...,...,...,...
1427,92004,Nanterre - Université,"48.901365, 2.212693",Nanterre,20.0,16.389831,0.0,0.0
1428,92005,Gare de Nanterre Ville,"48.8950295, 2.1957932",Nanterre,43.0,21.022901,0.0,0.0
1429,92006,Place Nelson Mandela,"48.897874318180556, 2.2182820737361912",Nanterre,30.0,5.030612,121.0,1.0
1430,92007,Pesaro - Préfecture,"48.89577046284005, 2.223908342421055",Nanterre,22.0,6.164179,123.0,2.0
1431,92008,Hôtel de Ville de Nanterre,"48.892371898250424, 2.205548956990242",Nanterre,38.0,13.500000,0.0,0.0

In [62]:
availability['capacity'] = availability['capacity'].astype(int)
availability['unavailable_count'] = availability['unavailable_count'].astype(int)
availability.dtypes

ID                       object
nom                      object
coordinates              object
communes                 object
capacity                  int64
availability_bike       float64
unavailable_duration    float64
unavailable_count         int64
dtype: object

In [63]:
availability

,ID,nom,coordinates,communes,capacity,availability_bike,unavailable_duration,unavailable_count
0,10001,René Boulanger - Lancry,"48.8685433, 2.3600032",Paris,62,11.869707,0.0,0
1,10003,Hauteville - Bonne Nouvelle,"48.87077436024, 2.3496496368327",Paris,17,7.632075,119.0,2
2,10004,Metz - Faubourg Saint-Denis,"48.870893, 2.353521",Paris,48,17.184211,0.0,0
3,10005,Petites Ecuries - Faubourg Poissonnière,"48.87397217237368, 2.348388757504776",Paris,17,7.911932,0.0,0
4,10006,Petites Ecuries - Faubourg Saint-Denis,"48.87287120589831, 2.3542150855064397",Paris,28,13.638776,0.0,0
...,...,...,...,...,...,...,...,...
1427,92004,Nanterre - Université,"48.901365, 2.212693",Nanterre,20,16.389831,0.0,0
1428,92005,Gare de Nanterre Ville,"48.8950295, 2.1957932",Nanterre,43,21.022901,0.0,0
1429,92006,Place Nelson Mandela,"48.897874318180556, 2.2182820737361912",Nanterre,30,5.030612,121.0,1
1430,92007,Pesaro - Préfecture,"48.89577046284005, 2.223908342421055",Nanterre,22,6.164179,123.0,2
1431,92008,Hôtel de Ville de Nanterre,"48.892371898250424, 2.205548956990242",Nanterre,38,13.500000,0.0,0

In [64]:
geolocator = Nominatim(user_agent="postcode_extractor")

In [65]:
%%time
geolocator.reverse('48.87287120589831, 2.3542150855064397').raw.get('address').get('suburb')

CPU times: user 11 ms, sys: 8.39 ms, total: 19.3 ms
Wall time: 201 ms

'Paris 10e Arrondissement'

In [66]:
paris_stations = availability[availability['communes'] == 'Paris'][['nom', 'coordinates']]
paris_stations

,nom,coordinates
0,René Boulanger - Lancry,"48.8685433, 2.3600032"
1,Hauteville - Bonne Nouvelle,"48.87077436024, 2.3496496368327"
2,Metz - Faubourg Saint-Denis,"48.870893, 2.353521"
3,Petites Ecuries - Faubourg Poissonnière,"48.87397217237368, 2.348388757504776"
4,Petites Ecuries - Faubourg Saint-Denis,"48.87287120589831, 2.3542150855064397"
...,...,...
1419,Faubourg Poissonnière - Dunkerque,"48.880883445404436, 2.349934279918671"
1420,Milton - Manuel,"48.878249, 2.341181"
1421,Victoire - Chaussée d'Antin,"48.875065791004396, 2.3316738009452824"
1422,Bellefond - Maubeuge,"48.878255397645, 2.3452642187476"
1423,Faubourg Poissonniere - Delta,"48.882555807626765, 2.3497482016682625"

In [67]:
def extract_arr(coordinates):
    location = geolocator.reverse(coordinates)
    postcode = location.raw.get('address', {}).get('postcode')
    if postcode:
        arrondissement = 'Paris ' + str(postcode)[-2:] + 'e Arrondissement'
        return arrondissement
    else:
        return None

extract_arr(paris_stations['coordinates'][0])

'Paris 10e Arrondissement'

In [68]:
geolocator.reverse('48.8242469, 2.3186306').raw.get('address')

{'house_number': '8',
 'road': 'Avenue de la Porte de Châtillon',
 'city_block': 'Quartier de Plaisance',
 'neighbourhood': 'Paris 14e Arrondissement',
 'suburb': 'Paris',
 'city_district': 'Paris',
 'city': 'Paris',
 'ISO3166-2-lvl6': 'FR-75',
 'state': 'Île-de-France',
 'ISO3166-2-lvl4': 'FR-IDF',
 'region': 'France métropolitaine',
 'postcode': '75014',
 'country': 'France',
 'country_code': 'fr'}

In [69]:
def extract_postcode(coordinates):
    location = geolocator.reverse(coordinates)
    if location:
        address = location.raw.get('address')
        if address:
            postcode = address.get('postcode')
            return postcode
    return None

extract_postcode('48.8685433, 2.3600032')

'75010'

In [70]:
%%time
paris_stations['arrondissement']=paris_stations['coordinates'].apply(extract_arr)

CPU times: user 2.27 s, sys: 657 ms, total: 2.93 s
Wall time: 8min 11s

In [71]:
display(paris_stations)
paris_stations['arrondissement'].unique()

,nom,coordinates,arrondissement
0,René Boulanger - Lancry,"48.8685433, 2.3600032",Paris 10e Arrondissement
1,Hauteville - Bonne Nouvelle,"48.87077436024, 2.3496496368327",Paris 10e Arrondissement
2,Metz - Faubourg Saint-Denis,"48.870893, 2.353521",Paris 10e Arrondissement
3,Petites Ecuries - Faubourg Poissonnière,"48.87397217237368, 2.348388757504776",Paris 10e Arrondissement
4,Petites Ecuries - Faubourg Saint-Denis,"48.87287120589831, 2.3542150855064397",Paris 10e Arrondissement
...,...,...,...
1419,Faubourg Poissonnière - Dunkerque,"48.880883445404436, 2.349934279918671",Paris 10e Arrondissement
1420,Milton - Manuel,"48.878249, 2.341181",Paris 09e Arrondissement
1421,Victoire - Chaussée d'Antin,"48.875065791004396, 2.3316738009452824",Paris 09e Arrondissement
1422,Bellefond - Maubeuge,"48.878255397645, 2.3452642187476",Paris 09e Arrondissement
1423,Faubourg Poissonniere - Delta,"48.882555807626765, 2.3497482016682625",Paris 10e Arrondissement

array(['Paris 10e Arrondissement', 'Paris 01e Arrondissement',
       'Paris 02e Arrondissement', 'Paris 11e Arrondissement',
       'Paris 20e Arrondissement', 'Paris 12e Arrondissement',
       'Paris 71e Arrondissement', 'Paris 13e Arrondissement',
       'Paris 14e Arrondissement', 'Paris 50e Arrondissement',
       'Paris 15e Arrondissement', 'Paris 16e Arrondissement',
       'Paris 17e Arrondissement', 'Paris 08e Arrondissement',
       'Paris 18e Arrondissement', 'Paris 19e Arrondissement',
       'Paris 03e Arrondissement', 'Paris 04e Arrondissement',
       'Paris 05e Arrondissement', 'Paris 06e Arrondissement',
       'Paris 07e Arrondissement', 'Paris 09e Arrondissement'],
      dtype=object)

In [72]:
paris_stations.loc[paris_stations['nom'] == 'Gare de Lyon - Chalon', 'arrondissement'] = 'Paris 12e Arrondissement'
paris_stations.loc[paris_stations['nom'] == 'Jourdan - Cité Universitaire', 'arrondissement'] = 'Paris 14e Arrondissement'

In [73]:
paris_stations['arrondissement'].unique()

array(['Paris 10e Arrondissement', 'Paris 01e Arrondissement',
       'Paris 02e Arrondissement', 'Paris 11e Arrondissement',
       'Paris 20e Arrondissement', 'Paris 12e Arrondissement',
       'Paris 13e Arrondissement', 'Paris 14e Arrondissement',
       'Paris 15e Arrondissement', 'Paris 16e Arrondissement',
       'Paris 17e Arrondissement', 'Paris 08e Arrondissement',
       'Paris 18e Arrondissement', 'Paris 19e Arrondissement',
       'Paris 03e Arrondissement', 'Paris 04e Arrondissement',
       'Paris 05e Arrondissement', 'Paris 06e Arrondissement',
       'Paris 07e Arrondissement', 'Paris 09e Arrondissement'],
      dtype=object)

In [78]:
availability.loc[availability['communes'] == 'Paris', 'communes'] = paris_stations['arrondissement']

In [79]:
availability['communes'].unique()

array(['Paris 10e Arrondissement', 'Paris 01e Arrondissement',
       'Paris 02e Arrondissement', 'Paris 11e Arrondissement',
       'Paris 20e Arrondissement', 'Paris 12e Arrondissement',
       'Saint-Mandé', 'Paris 13e Arrondissement', 'Ivry-sur-Seine',
       'Paris 14e Arrondissement', 'Malakoff', 'Montrouge',
       'Paris 15e Arrondissement', 'Paris 16e Arrondissement',
       'Paris 17e Arrondissement', 'Paris 08e Arrondissement',
       'Paris 18e Arrondissement', 'Paris 19e Arrondissement', 'Pantin',
       'Boulogne-Billancourt', 'Clichy', 'Issy-les-Moulineaux', 'Clamart',
       'Suresnes', 'Vanves', 'Meudon', 'Neuilly-sur-Seine', 'Saint-Cloud',
       'Bagneux', 'Gennevilliers', 'La Garenne-Colombes',
       'Fontenay-aux-Roses', 'Bois-Colombes', 'Levallois-Perret',
       'Bourg-la-Reine', 'Sèvres', 'Châtillon', 'Sceaux', 'Chaville',
       'Villeneuve-la-Garenne', 'Courbevoie', "Ville-d'Avray",
       'Rueil-Malmaison', 'Asnières-sur-Seine', 'Colombes', 'Puteaux',
       'Bobigny', 'Paris 03e Arrondissement', 'Montreuil',
       'Rosny-sous-Bois', 'Noisy-le-Sec', 'Bagnolet', 'Saint-Denis',
       'Romainville', 'Les Lilas', 'Aubervilliers',
       'Le Pré-Saint-Gervais', 'Saint-Ouen-sur-Seine',
       'Paris 04e Arrondissement', 'Arcueil', 'Fontenay-sous-Bois',
       'Nogent-sur-Marne', 'Alfortville', 'Charenton-le-Pont', 'Cachan',
       'Gentilly', 'Le Kremlin-Bicêtre', 'Vincennes', 'Joinville-le-Pont',
       'Vitry-sur-Seine', 'Saint-Maurice', 'Champigny-sur-Marne',
       'Choisy-le-Roi', 'Maisons-Alfort', 'Villejuif',
       'Paris 05e Arrondissement', 'Argenteuil',
       'Paris 06e Arrondissement', 'Paris 07e Arrondissement',
       'Paris 09e Arrondissement', 'Nanterre'], dtype=object)

In [80]:
availability[['latitude', 'longitude']] = availability['coordinates'].str.split(',', expand=True).astype(float)
availability['postcode'] = availability['coordinates'].apply(extract_postcode)
availability

,ID,nom,coordinates,communes,capacity,availability_bike,unavailable_duration,unavailable_count,latitude,longitude,postcode
0,10001,René Boulanger - Lancry,"48.8685433, 2.3600032",Paris 10e Arrondissement,62,11.869707,0.0,0,48.868543,2.360003,75010
1,10003,Hauteville - Bonne Nouvelle,"48.87077436024, 2.3496496368327",Paris 10e Arrondissement,17,7.632075,119.0,2,48.870774,2.349650,75010
2,10004,Metz - Faubourg Saint-Denis,"48.870893, 2.353521",Paris 10e Arrondissement,48,17.184211,0.0,0,48.870893,2.353521,75010
3,10005,Petites Ecuries - Faubourg Poissonnière,"48.87397217237368, 2.348388757504776",Paris 10e Arrondissement,17,7.911932,0.0,0,48.873972,2.348389,75010
4,10006,Petites Ecuries - Faubourg Saint-Denis,"48.87287120589831, 2.3542150855064397",Paris 10e Arrondissement,28,13.638776,0.0,0,48.872871,2.354215,75010
...,...,...,...,...,...,...,...,...,...,...,...
1427,92004,Nanterre - Université,"48.901365, 2.212693",Nanterre,20,16.389831,0.0,0,48.901365,2.212693,92000
1428,92005,Gare de Nanterre Ville,"48.8950295, 2.1957932",Nanterre,43,21.022901,0.0,0,48.895029,2.195793,92000
1429,92006,Place Nelson Mandela,"48.897874318180556, 2.2182820737361912",Nanterre,30,5.030612,121.0,1,48.897874,2.218282,92000
1430,92007,Pesaro - Préfecture,"48.89577046284005, 2.223908342421055",Nanterre,22,6.164179,123.0,2,48.895770,2.223908,92000
1431,92008,Hôtel de Ville de Nanterre,"48.892371898250424, 2.205548956990242",Nanterre,38,13.500000,0.0,0,48.892372,2.205549,92000

Series([], Name: communes, dtype: object)

In [81]:
availability.to_csv('availability.csv', index=False)

In [82]:
durations[['latitude', 'longitude']] = durations['coordinates'].str.split(',', expand=True).astype(float)
durations['postcode'] = durations['coordinates'].apply(extract_postcode)
durations

,ID,nom,coordinates,communes,capacity,available_time,unavailable_time,unavailable_duration,latitude,longitude,postcode
0,10003,Hauteville - Bonne Nouvelle,"48.87077436024, 2.3496496368327",Paris,17.0,2024-02-13 23:01:39+01:00,2024-02-13 22:03:47+01:00,58,48.870774,2.349650,75010
1,10003,Hauteville - Bonne Nouvelle,"48.87077436024, 2.3496496368327",Paris,17.0,2024-02-14 05:03:02+01:00,2024-02-14 04:02:41+01:00,61,48.870774,2.349650,75010
2,10009,Mairie du 10ème,"48.872089449907, 2.3575825989246",Paris,19.0,2024-02-12 15:53:11+01:00,2024-02-12 14:51:43+01:00,62,48.872089,2.357583,75010
3,10009,Mairie du 10ème,"48.872089449907, 2.3575825989246",Paris,19.0,2024-02-12 17:00:10+01:00,2024-02-12 15:53:11+01:00,67,48.872089,2.357583,75010
4,10013,Alibert - Jemmapes,"48.871044051984, 2.3661044619878",Paris,60.0,2024-02-14 09:59:01+01:00,2024-02-14 09:01:31+01:00,58,48.871044,2.366104,75010
...,...,...,...,...,...,...,...,...,...,...,...
1445,9117,Bellefond - Maubeuge,"48.878255397645, 2.3452642187476",Paris,31.0,2024-02-13 17:00:52+01:00,2024-02-13 15:03:28+01:00,118,48.878255,2.345264,75009
1446,9117,Bellefond - Maubeuge,"48.878255397645, 2.3452642187476",Paris,31.0,2024-02-14 10:00:45+01:00,2024-02-14 09:00:11+01:00,61,48.878255,2.345264,75009
1447,92006,Place Nelson Mandela,"48.897874318180556, 2.2182820737361912",Nanterre,30.0,2024-02-13 21:01:10+01:00,2024-02-13 19:00:17+01:00,121,48.897874,2.218282,92000
1448,92007,Pesaro - Préfecture,"48.89577046284005, 2.223908342421055",Nanterre,22.0,2024-02-12 21:56:37+01:00,2024-02-12 20:56:11+01:00,61,48.895770,2.223908,92000
1449,92007,Pesaro - Préfecture,"48.89577046284005, 2.223908342421055",Nanterre,22.0,2024-02-13 17:58:54+01:00,2024-02-13 16:56:56+01:00,62,48.895770,2.223908,92000

In [83]:
durations.to_csv('durations.csv', index=False)

In [85]:
df[['latitude', 'longitude']] = df['coordinates'].str.split(',', expand=True).astype(float)

In [88]:
#df['postcode'] = df['coordinates'].apply(extract_postcode)
#df

In [86]:
df.to_csv('df.csv', index=False)